2021-01-25 09:13:08,863 INFO    MainThread:1292 [wandb_setup.py:_flush():70] setting env: {}
2021-01-25 09:13:08,863 INFO    MainThread:1292 [wandb_setup.py:_flush():70] multiprocessing start_methods=fork,spawn,forkserver
2021-01-25 09:13:08,863 INFO    MainThread:1292 [wandb_setup.py:_flush():70] setting login settings: {}
2021-01-25 09:13:08,863 INFO    MainThread:1292 [wandb_setup.py:_flush():70] setting login settings: {'api_key': '3a4187cb1d335b13cc8a3b4805d70b3818fdd4f5'}
2021-01-25 09:13:08,864 INFO    MainThread:1292 [wandb_init.py:_log_setup():303] Logging user logs to /root/CassavaCompetition/wandb/run-20210125_091308-2l20saop/logs/debug.log
2021-01-25 09:13:08,864 INFO    MainThread:1292 [wandb_init.py:_log_setup():304] Logging internal logs to /root/CassavaCompetition/wandb/run-20210125_091308-2l20saop/logs/debug-internal.log
2021-01-25 09:13:10,777 INFO    MainThread:1292 [wandb_run.py:_console_start():1237] atexit reg
2021-01-25 09:13:10,778 INFO    MainThread:1292 [wandb_run.py:_redirect():1104] redirect: SettingsConsole.REDIRECT
2021-01-25 09:13:10,778 INFO    MainThread:1292 [wandb_run.py:_redirect():1107] Redirecting console.
2021-01-25 09:13:10,778 INFO    MainThread:1292 [redirect.py:install():204] install start
2021-01-25 09:13:10,779 INFO    MainThread:1292 [redirect.py:install():219] install stop
2021-01-25 09:13:10,780 INFO    MainThread:1292 [redirect.py:install():204] install start
2021-01-25 09:13:10,780 INFO    MainThread:1292 [redirect.py:install():219] install stop
2021-01-25 09:13:10,780 INFO    MainThread:1292 [wandb_run.py:_redirect():1151] Redirects installed.
2021-01-25 09:13:24,016 INFO    MainThread:1292 [wandb_run.py:_atexit_cleanup():1207] got exitcode: 1
2021-01-25 09:13:24,017 INFO    MainThread:1292 [wandb_run.py:_restore():1179] restore
2021-01-25 09:13:24,017 INFO    MainThread:1292 [redirect.py:uninstall():223] uninstall start
2021-01-25 09:13:24,017 INFO    MainThread:1292 [redirect.py:_stop():278] _stop: stdout
2021-01-25 09:13:24,017 INFO    MainThread:1292 [redirect.py:_stop():284] _stop closed: stdout
2021-01-25 09:13:24,018 INFO    stdout    :1292 [redirect.py:_pipe_relay():120] relay done saw last write: stdout
2021-01-25 09:13:24,019 INFO    stdout    :1292 [redirect.py:_pipe_relay():136] relay done done: stdout
2021-01-25 09:13:24,019 INFO    MainThread:1292 [redirect.py:_stop():290] _stop joined: stdout
2021-01-25 09:13:24,019 INFO    MainThread:1292 [redirect.py:_stop():292] _stop rd closed: stdout
2021-01-25 09:13:24,019 INFO    MainThread:1292 [redirect.py:uninstall():227] uninstall done
2021-01-25 09:13:24,019 INFO    MainThread:1292 [redirect.py:uninstall():223] uninstall start
2021-01-25 09:13:24,019 INFO    MainThread:1292 [redirect.py:_stop():278] _stop: stderr
2021-01-25 09:13:24,019 INFO    MainThread:1292 [redirect.py:_stop():284] _stop closed: stderr
2021-01-25 09:13:24,020 INFO    stderr    :1292 [redirect.py:_pipe_relay():120] relay done saw last write: stderr
2021-01-25 09:13:24,020 INFO    stderr    :1292 [redirect.py:_pipe_relay():136] relay done done: stderr
2021-01-25 09:13:24,021 INFO    MainThread:1292 [redirect.py:_stop():290] _stop joined: stderr
2021-01-25 09:13:24,021 INFO    MainThread:1292 [redirect.py:_stop():292] _stop rd closed: stderr
2021-01-25 09:13:24,021 INFO    MainThread:1292 [redirect.py:uninstall():227] uninstall done
2021-01-25 09:13:24,024 INFO    MainThread:1292 [wandb_run.py:_wait_for_finish():1324] got exit ret: uuid: "8137d28e36074eed9bb566cd5d16cf36"
response {
  poll_exit_response {
    file_counts {
      wandb_count: 1
    }
    pusher_stats {
      uploaded_bytes: 648
      total_bytes: 648
    }
  }
}

2021-01-25 09:13:26,029 INFO    MainThread:1292 [wandb_run.py:_wait_for_finish():1324] got exit ret: uuid: "9bc85474fefc4dd2849375dfcbacf20c"
response {
  poll_exit_response {
    done: true
    exit_result {
    }
    file_counts {
      wandb_count: 5
    }
    pusher_stats {
      uploaded_bytes: 57315
      total_bytes: 57315
    }
  }
}

2021-01-25 09:13:27,178 INFO    MainThread:1292 [wandb_run.py:_show_files():1536] logging synced files
2021-01-25 09:13:27,181 INFO    MainThread:1292 [internal.py:handle_exit():138] Internal process exited
